version: "1.0"
indexMode: INDEX_SPARQL_ENDPOINT
sparqlEndpoint: http://virtuoso:8890/sparql
indexFields:
  - fieldName: annotatedCount
    documentVariable: oeoClass
    type: numeric
    query: >
      SELECT ?oeoClass (COUNT(DISTINCT ?mod) as ?annotatedCount) WHERE {
          GRAPH ?g {
            ?mod a <https://dataid.dbpedia.org/moss#OEMetadataMod> .
            ?s <https://saref.etsi.org/core/isAbout> ?oeoClass .
          }
      } GROUP BY ?oeoClass
