version: "1.0"
indexPath: ./index
exactMatchBoost: 10
prefixMatchBoost: 5
fuzzyMatchBoost: 2
fuzzyEditDistance: 2
fuzzyPrefixLength: 2
boostFormula: 1+annotatedCount
maxResults: 1000
format: JSON
minScore: 0.1
queryFields:
  - fieldName: label
    weight: 10
    highlight: true
    tokenize: true
    queryByDefault: true
  - fieldName: altLabel
    weight: 5
    highlight: true
    tokenize: true
    queryByDefault: true
  - fieldName: description
    weight: 1
    highlight: true
    tokenize: true
    queryByDefault: true
  - fieldName: type
    weight: 1
    highlight: false
    tokenize: false
    exact: true
    required: true
  - fieldName: classId
    weight: 10
    highlight: false
    tokenize: true
    queryByDefault: false
